applications:
  - name: app-argocd
    identifier_uris: api://argocd
    homepage_url: https://argocd.decort.tech
    web_redirect_uris: [https://argocd.decort.tech/auth/callback]
    public_client_redirect_uris: [http://localhost:8085/auth/callback]
    group_membership_claims: ApplicationGroup
    access_group: grp-argocd-admin
    app_roles:
      - name: argocd-access
        description: Allow ArgoCD Web Access
        allowed_member_types: [User]
        reference: Users.All

  - name: app-terraform
    identifier_uris: api://terraform
    homepage_url: ""
    web_redirect_uris: []
    public_client_redirect_uris: []
    group_membership_claims: ""
    access_group: ""
