applications:
  - name: app-argocd
    identifier_uris: api://argocd
    web:
      homepage_url: https://argocd.decort.tech
      redirect_uris: [https://argocd.decort.tech/auth/callback]
    public_client:
      redirect_uris: [http://localhost:8085/auth/callback]
    group_membership_claims: ApplicationGroup
    access_group: grp-argocd-admin
    resource_access:
      - id: df021288-bdef-4463-88db-98f22de89214 # Users.ALl
        type: Role
    app_roles:
      - name: argocd-access
        description: Allow ArgoCD Web Access
        allowed_member_types: [User]
        reference: Users.All

  - name: app-terraform
    identifier_uris: api://terraform
    web:
      homepage_url: null
      redirect_uris: []
    public_client:
      redirect_uris: []
    group_membership_claims: ApplicationGroup
    access_group: sg-dct-admin
    resource_access:
      - id: ba92f5b4-2d11-453d-a403-e96b0029c9fe # Storage Blob Data Contributor
        type: Role
    app_roles:
      - name: terraform-backend
        description: Allow Terraform Backend Access
        allowed_member_types: [Application]
        reference: Storage.All

  - name: app-external-secrets
    identifier_uris: api://external-secrets
    web:
      homepage_url: null
      redirect_uris: []
    public_client:
      redirect_uris: []
    group_membership_claims: ApplicationGroup
    access_group: sg-dct-admin
    resource_access:
      - id: f25e0fa2-a7c8-4377-a976-54943a77a395 # Key Vault Contributor
        type: Role
    app_roles:
      - name: external-secrets-kv-access
        description: Allow External Secrets to Key Vault
        allowed_member_types: [Application]
        reference: KeyVault.LabInfra.All

  - name: app-vault-unseal
    identifier_uris: api://vault
    web:
      homepage_url: null
      redirect_uris: []
    public_client:
      redirect_uris: []
    group_membership_claims: ApplicationGroup
    access_group: sg-dct-admin
    resource_access:
      - id: df021288-bdef-4463-88db-98f22de89214 # Users.All
        type: Role
    app_roles:
      - name: vault-user-read
        description: Allow Vault to Read User info
        allowed_member_types: [Application]
        reference: User.Read
      - name: vault-application-rw
        description: Allow Vault to Read and Write the Application
        reference: Application.ReadWrite.All
        allowed_member_types: [Application]
      - name: vault-directory-rw
        description: Allow Vault to Read and Write the Directory
        allowed_member_types: [Application]
        reference: Directory.ReadWrite.All
